Attempt to switch to Ubuntu 20.04
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
https://github.com/rspec/rspec-core/actions/runs/4314616470/jobs/7527887352:

Run ruby/setup-ruby@v1
Error: Error: Unsupported platform ubuntu-18.04
    at Module.getAvailableVersions (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:67995:11)